import { useMemo } from 'react';
import { useTexture } from '@react-three/drei';
import { useThree } from '@react-three/fiber';
import * as THREE from 'three';

/**
 * These began as Poly Haven's 1k JPEG sets (CC0) pulled straight from their CDN,
 * which came to 14.8 MB before a single frame could be drawn. They are now
 * served from this site as 512px WebP — 1.7 MB for the same thirty files, an
 * 88% cut — because the on-screen texel density here is set by each surface's
 * `repeat`, not by the source resolution, so the extra pixels were being thrown
 * away by the sampler anyway. See the note on preloading at the foot of this
 * file for why they are all requested at once.
 */
const BASE = '/textures';

/**
 * Three maps per surface:
 *   diff  colour
 *   nor   normals — the surface relief. Without this everything reads as flat
 *         plastic no matter how good the colour is.
 *   arm   ambient occlusion / roughness / metalness packed into RGB
 *
 * Little Workshop's showroom ships albedo + normal + metallic-smoothness for
 * every single surface — there is no untextured material anywhere in it. That
 * is most of why it reads as photographic, so nothing here goes bare either.
 */
const set = (name: string) => ({
  map: `${BASE}/${name}/diff.webp`,
  normalMap: `${BASE}/${name}/nor.webp`,
  aoMap: `${BASE}/${name}/arm.webp`,
  roughnessMap: `${BASE}/${name}/arm.webp`,
});

export const TEXTURE_SETS = {
  concrete: set('concrete'),
  stone: set('stone'),
  grass: set('grass'),
  bark: set('bark'),
  plaster: set('plaster'),
  planks: set('planks'),
  oak: set('oak'),
  fabric: set('fabric'),
  carpet: set('carpet'),
  marble: set('marble'),
};

/**
 * Every texture is requested the moment this module is evaluated, rather than
 * when the component that happens to need it first mounts.
 *
 * The obvious reason is that thirty parallel requests beat five waves of six.
 * The less obvious one is that it is the only way the loading figure can mean
 * anything: three's loading manager reports loaded/total, and `total` only
 * counts what has been queued so far. Mounting components in waves makes that
 * fraction reach 100% at the end of every wave, so the number on the loading
 * screen hit 100 within a second and then sat there for the rest of the load.
 * Queueing the lot up front gives the manager the real denominator from the
 * start.
 */
/**
 * The canvases that hang on the walls. Generated by scripts/make-art.mjs into
 * public/art — swap any one of these files for a photograph of your own and it
 * appears in its frame at the next build, no code change: `Artwork` reads the
 * picture's proportions off the texture, so a different aspect ratio just
 * gives a differently shaped frame.
 */
export const ART = {
  horizon: '/art/horizon.webp',
  strata: '/art/strata.webp',
  arcs: '/art/arcs.webp',
  /**
   * The portrait over the living room sideboard — the frame the camera passes
   * closest to. Replace it with `node scripts/frame-photo.mjs <your-photo>`,
   * which handles a cut-out subject and the 2:3 print ratio; nothing here
   * needs changing.
   */
  portrait: '/art/portrait.webp',
};

export function useArt() {
  const tex = useTexture(ART);
  return useMemo(() => {
    // Artwork is colour, not data — without this the pictures render washed
    // out, the same way an albedo map would.
    for (const t of Object.values(tex)) t.colorSpace = THREE.SRGBColorSpace;
    return tex;
  }, [tex]);
}

useTexture.preload([
  ...new Set(Object.values(TEXTURE_SETS).flatMap((s) => Object.values(s))),
  ...Object.values(ART),
]);

/** Repeats a loaded set and returns props ready to spread onto a material. */
export function useTiled(
  which: keyof typeof TEXTURE_SETS,
  repeat: [number, number]
) {
  const tex = useTexture(TEXTURE_SETS[which]);
  const maxAniso = useThree((s) => s.gl.capabilities.getMaxAnisotropy());

  return useMemo(() => {
    // useTexture caches by URL, so clone before mutating or every surface
    // sharing this set inherits the last repeat that was applied.
    const cloned = {
      map: tex.map.clone(),
      normalMap: tex.normalMap.clone(),
      aoMap: tex.aoMap.clone(),
      roughnessMap: tex.roughnessMap.clone(),
    };

    for (const t of Object.values(cloned)) {
      t.wrapS = t.wrapT = THREE.RepeatWrapping;
      t.repeat.set(repeat[0], repeat[1]);
      // Without anisotropy a tiled floor or lawn smears into grey mush the
      // moment the camera looks along it — which is exactly what a walkthrough
      // camera does for most of its journey.
      t.anisotropy = maxAniso;
      t.needsUpdate = true;
    }
    cloned.map.colorSpace = THREE.SRGBColorSpace;

    return cloned;
  }, [tex, repeat, maxAniso]);
}

/**
 * A painted / plain surface that still has relief. Returns the plaster set's
 * normal and roughness with no colour map, so `color` on the material still
 * drives the hue. Use it for anything that would otherwise be a bare
 * meshStandardMaterial — steps, stair treads, ceilings, trim, furniture.
 */
export function useSurface(
  repeat: [number, number] = [3, 3],
  which: keyof typeof TEXTURE_SETS = 'plaster',
  strength = 0.35
) {
  const tex = useTexture({
    normalMap: TEXTURE_SETS[which].normalMap,
    roughnessMap: TEXTURE_SETS[which].roughnessMap,
  });
  const maxAniso = useThree((s) => s.gl.capabilities.getMaxAnisotropy());

  return useMemo(() => {
    const cloned = {
      normalMap: tex.normalMap.clone(),
      roughnessMap: tex.roughnessMap.clone(),
    };
    for (const t of Object.values(cloned)) {
      t.wrapS = t.wrapT = THREE.RepeatWrapping;
      t.repeat.set(repeat[0], repeat[1]);
      t.anisotropy = maxAniso;
      t.needsUpdate = true;
    }
    return { ...cloned, normalScale: new THREE.Vector2(strength, strength) };
  }, [tex, repeat, maxAniso, strength]);
}
